# Generated by Django 6.1.1 on 2026-10-03 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(blank=True, choices=[('architect', 'Architect'), ('engineer', 'Software Engineer'), ('pm', 'Product Manager'), ('data', 'Data Scientist'), ('ml', 'ML Engineer'), ('designer', 'UX Designer'), ('other', 'Other')], default='engineer', max_length=20)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('background', models.TextField(blank=True, help_text='Resume / skills summary used as default context.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
