# Generated by Django 6.1.1 on 2026-10-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_add_plan_stripe_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptentry',
            name='speaker_type',
            field=models.CharField(choices=[('microphone', 'Microphone'), ('system', 'System Audio'), ('note', 'Note')], default='microphone', max_length=20),
        ),
    ]
