# Generated by Django 6.1.1 on 2026-10-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0007_alter_transcriptentry_speaker_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('backup', 'SQLite → MySQL'), ('restore', 'MySQL → SQLite')], max_length=10)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='running', max_length=10)),
                ('records_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('triggered_by', models.CharField(blank=True, max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
