# Generated by Django 6.1.1 on 2026-10-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0010_seed_prompt_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompttemplate',
            name='template_type',
            field=models.CharField(choices=[('ai_help', 'AI Help'), ('meeting_ai', 'Meeting AI'), ('conversation', 'Conversation')], default='ai_help', max_length=20),
        ),
    ]
