# Generated by Django 6.1.1 on 2026-10-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0011_add_conversation_template_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='prep_notes',
            field=models.TextField(blank=True, help_text='Interview preparation tips, talking points, and STAR examples.'),
        ),
    ]
