# Generated by Django 6.1.1 on 2026-10-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0014_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=10),
        ),
    ]
